---
title: "Bitcoin_Prediction"
author: "s3692260_Dhilip_Surya_Rajendran"
date: "  2019"
output: html_document
---


The aim of this project is to predict the bitcoin price for the next 3 months. 



The necessary library packages are loaded.
```{r}
library(forecast)
library(ggplot2)
library(ggfortify)
library(ggplot2)
library(highcharter)
library(zoo)
library(tseries)
```



```{r}
csv_data <- read.csv('C:/Users/dhili/Downloads/market-price.csv' ,header = FALSE)
csv_df <- data.frame(csv_data)

csv_df$Close <- csv_df$V2
edf  <- csv_df
head(edf)
tail(edf)
edf$v7_MA = ma(edf$Close, order=7)
```

The data is being uploaded from the drive.

```{r}
#STL  
edf_ma <- ts(na.omit(edf$v7_MA), frequency=10)
decomp_edf <- stl(edf_ma, s.window="periodic")
#plot(decomp_rental)
adj_edf <- seasadj(decomp_edf)
```

```{r}

#hfit<-HoltWinters(adj_edf)
#hfit<-auto.arima(adj_edf)
hfit<-tbats(adj_edf)
f2<-forecast(hfit, h=(30*3))
```

```{r}

df <- fortify(f2)
df$Data<-round(df$Data)
df$Fitted<-round(df$Fitted)
df$Index<-seq(as.Date("2018-07-20"), (as.Date("2019-07-19")+(30*(3))),length.out=length(df$Index))


```


```{r}

highchart(type = "stock") %>% 
  hc_legend(enabled = TRUE) %>% 
  hc_title(text = "Bitcoin Prediction using Prediction models") %>% 
  hc_add_series(df, "line", hcaes(Index, Data), name = "Actual Price", color="black") %>% 
  hc_add_series(df, "line", hcaes(Index, Fitted), name = "Predicted Price") %>%
  hc_add_series(df, "line", hcaes(Index, `Point Forecast`), name = "Forecasted Price") %>% 
  hc_add_series(df, "arearange", hcaes(Index, low = `Lo 95`, high = `Hi 95`), name = "Prediction Interval") 



```



